### ISSUE TITLE
Unable to set custom bot as message sender

### ISSUE THREAD

**Issue by nmeirik** [cleentfaar/slack#17] opened 2015-05-09 18:05 UTC
Using the ChatPostMessagePayload, I am unable to set the bot I've created as the sender. I'm setting the username of a bot I've created as the username, but messages are still posted as the slackbot. I can see from the [documentation](https://api.slack.com/methods/chat.postMessage) that the API supports an as_user parameter which might be useful since I'm authenticating with the API token of the bot, but it appears that the repository does not support this.

**Comment by cleentfaar** [comment] 2015-05-16 17:51
Hi @nmeirik!

First of all, thanks for reporting the issue! However, using the code supplied below, I'm having trouble reproducing it:

![screen shot 2015-05-16 at 19 48 35](https://cloud.githubusercontent.com/assets/795661/7667341/939d0754-fc04-11e4-9ec9-c925965f150a.png)

Could you copy/paste the following code and make the necessary changes (replace with your token), then let me know what results you get? 

Also let me know which version you are working with, thanks!

```php
$payload = new ChatPostMessagePayload();
$payload->setUsername('mybotname');
$payload->setText('My text');
$payload->setChannel('#general');

$apiClient = new ApiClient('your-api-token-here');
$response = $apiClient->send($payload);

if ($response->isOk()) {
    echo 'This worked!';
} else {
    echo 'Something went wrong: '.$response->getErrorExplanation();
}

exit;
```

**Comment by agopaul** [comment] 2015-05-20 09:15
I'm having the same problem. When you create a bot from https://mydomain.slack.com/services/new/bot, you can choose a name and an avatar for the bot. The ChatPostMessagePayload payload works just fine with the API key provided for the bot, however, the name and avatar used is the default one (like in your screenshot).

After spending some time on the Slack documentation, I think I may have found the problem: in order to use the bot interactively, you have to integrate the Real Time Messaging API (https://api.slack.com/rtm) which rely on websockets to exchange messages with a bot (bidirectionally).

**Comment by nmeirik** [comment] 2015-05-20 09:18
@agopaul Thanks for your input. Have you tried this out in real life? And do you know of a PHP library which supports this interaction?

**Comment by agopaul** [comment] 2015-05-20 09:41
Nope, I haven't tried yet, although it seems quite straightforward to integrate:
1) Implement the _rtm.start_ API call which gives you the ws address (I think it's missing in this library)
2) Write a script which opens the ws connection and pushes the message in the stream

A better integration would be writing a PHP daemon which stays connected to the ws stream and exchanges messages with your application using queues, but that might be overkill in your case.

**Comment by cleentfaar** [comment] 2015-05-20 19:36
Thanks for researching this a bit guys!

I guess I misunderstood the problem, so just to be clear: 

**What should work already**: the `ChatPostMessagePayload` should allow you to send a message with any username you want (as shown/proven in my screenshot above), to a channel of your choice. Provided you use a token as described in the installation doc. If this does not work for you then thats a bug/token issue.

However...

**What might not work**: it seems you want to send a message and interact with someone else as an (existing?) webhook/bot. Is this correct?

Whatever the case, I'm happy to merge any ideas you guys might have for this. 

Heck, I might get some time for it the coming weekend. It would probably be a separate package like `slack-rtm`.

If any of you want to get some sort of collab going for this just hit me an email and I'll invite you to my (hobby) slack team: info@casleentfaar.com.

**Comment by cleentfaar** [comment] 2015-05-20 19:46
Btw @nmeirik I think your issue will be solved by just adding the `as_user` property, if all you want is to send a message as an existing user.

But if you want to create a slack client yourself you will indeed require an RTM implementation: the basic api is not suitable for that anyway since it is rate limited.

**Comment by nmeirik** [comment] 2015-05-21 06:29
@cleentfaar My use case specifically is that I have created a bot representing one of our systems, and I want to be able to post DMs to my colleagues as that bot.

**Comment by Zxurian** [comment] 2015-06-01 18:53
@cleentfaar I have the same use as @nmeirik 
Some of the confusion may come from the `username` property of a chat payload. When you set that on a payload, it doesn't actually change who the message is originating from, just the display of the username on the Slack client itself.
> example: if you send a message to a channel or group with a username set, then you'll see the message as "coming from" that username, even though `slackbot` is the user actually sending the message.
> if you send a direct message to another @user you'll see the message originates from `slackbot` under the Direct Messages, even though under the chat history, the username will be set to whatever specify

What we're trying to do, which I think isn't possible using the Webhooks api (which is what this is based off of) is send a message originating from the bot user itself. Like the research that has been mentioned here, I think the only way to do that is to use the Websocket API. The only problem is I don't think it will be able to be added to this repo, but like @cleentfaar said, a separate rpo with rtm implementation, since it will have to be equipped to receive as well as send.

**Comment by cleentfaar** [comment] 2015-09-20 12:44
@Zxurian I'm catching up on all the issues I have missed the last few months, do you think I can close this one or is there still something that needs fixing on my end? 

There probably already is an RTM implementation available on GitHub, so I think will not be looking into this very soon.

Perhaps some clarification in the documentation is needed to prevent other people from expecting this behaviour? Let me know and I will be happy to add it.

**Comment by cleentfaar** [comment] 2015-09-20 13:38
Whilst backtracking I came across a related PR: https://github.com/cleentfaar/slack/pull/32, do you think it can fix this issue properly?

**Comment by Zxurian** [comment] 2015-09-25 14:14
it's a moot issue when using webhooks api. Whatever token you use to authenticate with, that's what user the message will come from. The actual username display on slack is minor. Aka, if your using a token for `userA`, and set `username` to `special user`. What will happen is in slack the message will come from `userA`, but within the actual message log, the username will be changed to `special user` for that message alone

**Comment by cleentfaar** [comment] 2015-09-30 11:46
Closing this as it seems this is not something the webhooks api supports; it only 'fakes' another user in Slack chat. You need the RTM implementation to send it as someone else then the token user.

**Closed by cleentfaar** 2015-09-30 11:46 UTC
